from selenium import webdriver
driver = webdriver.Chrome()
driver.get("http://practice.automationtesting.in/")
driver.maximize_window()
driver.execute_script("window.scrollBy(0, 600);")
driver.get("http://practice.automationtesting.in/product/selenium-ruby/")
rev_btn = driver.find_element_by_css_selector("#product-160 > div.woocommerce-tabs.wc-tabs-wrapper > ul > li.reviews_tab > a")
rev_btn.click()
stars_btn = driver.find_element_by_css_selector("#commentform > p.comment-form-rating > p > span > a.star-5")
stars_btn.click()
comment = driver.find_element_by_id("comment")
comment.send_keys("Very Nice Book!")
name = driver.find_element_by_id("author")
name.send_keys("Andrey Velikolepniy")
milo = driver.find_element_by_id("email")
milo.send_keys("Velikolepnoe_Milo@bk.ru")
sub_btn = driver.find_element_by_id("submit")
sub_btn.click()