import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium import webdriver
driver = webdriver.Chrome()
driver.get("http://practice.automationtesting.in/")
driver.maximize_window()
shop_btn = driver.find_element_by_id("menu-item-40")
shop_btn.click()
driver.execute_script("window.scrollBy(0, 300);")
kniga = driver.find_element_by_css_selector("#content > ul > li.post-182 > a.button.product_type_simple.add_to_cart_button.ajax_add_to_cart")
kniga.click()
time.sleep(3)
korzina = driver.find_element_by_css_selector("#wpmenucartli > a > span.cartcontents")
korzina.click()
button = WebDriverWait(driver, 3).until(
    EC.element_to_be_clickable((By.CSS_SELECTOR, "#page-34 > div > div.woocommerce > div > div > div > a"))
)
button.click()
name = driver.find_element_by_id("billing_first_name")
name.send_keys("Andrey")
last = driver.find_element_by_id("billing_last_name")
last.send_keys("Ruslanovich")
milo = driver.find_element_by_id("billing_email")
milo.send_keys("VelikolepnoeMilo@bk.ru")
phone = driver.find_element_by_id("billing_phone")
phone.send_keys("89505652200")
adress1 = driver.find_element_by_id("billing_address_1")
adress1.send_keys("Kommunisticheska")
city = driver.find_element_by_id("billing_city")
city.send_keys("Syktyvkar")
state = driver.find_element_by_id("billing_state")
state.send_keys("Russia")
zipp = driver.find_element_by_id("billing_postcode")
zipp.send_keys("167001")
driver.execute_script("window.scrollBy(0, 600);")
time.sleep(3)
oplata = driver.find_element_by_id("payment_method_cheque")
oplata.click()
place = driver.find_element_by_id("place_order")
place.click()
time.sleep(3)
proverka = WebDriverWait(driver, 3).until(
    EC.text_to_be_present_in_element((By.CSS_SELECTOR, "#page-35 > div > div.woocommerce > p.woocommerce-thankyou-order-received"), "Thank you. Your order has been received.")
)
proverka2 = WebDriverWait(driver, 3).until(
    EC.text_to_be_present_in_element((By.CSS_SELECTOR, "#page-35 > div > div.woocommerce > ul > li.method > strong"), "Check Payments")
)